name: Build and Release SafeBox (Multi-Platform)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build binaries
        run: npm run make

      - name: Archive Electron Forge output
        run: |
          cd out
          zip -r ../safebox-out.zip .
        shell: bash

      - name: Upload zipped output to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: safebox-out.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
